# Generated by Django 4.0.3 on 2022-03-31 10:13

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Filmwork',
            fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False,
                                            primary_key=True,
                                            serialize=False)),
                    ('created', models.DateTimeField(
                        auto_now_add=True, verbose_name='created')),
                    ('modified', models.DateTimeField(
                        auto_now=True, verbose_name='modified')),
                    (
                        'title',
                        models.CharField(max_length=255, verbose_name='name')),
                    ('description', models.TextField(
                        blank=True, verbose_name='description')),
                    ('creation_date', models.DateTimeField(
                        auto_now_add=True, verbose_name='creation_date')),
                    ('rating', models.FloatField(blank=True, validators=[
                        django.core.validators.MinValueValidator(
                            0), django.core.validators.MaxValueValidator(100)],
                        verbose_name='rating')),
                    ('type', models.CharField(choices=[
                        ('movie', 'Movie'), ('tv_show', 'Tv show')],
                        max_length=60,
                        verbose_name='type')),
                    ],
            options={
                'verbose_name': 'filmwork',
                'verbose_name_plural': 'filmworks',
                'db_table': 'content"."film_work',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True,
                                        serialize=False)),
                ('created', models.DateTimeField(
                    auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(
                    auto_now=True, verbose_name='modified')),
                ('name', models.CharField(
                    max_length=255, verbose_name='name')),
                ('description', models.TextField(
                    blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'db_table': 'content"."genre',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True,
                                        serialize=False)),
                ('created', models.DateTimeField(
                    auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(
                    auto_now=True, verbose_name='modified')),
                ('full_name', models.CharField(
                    max_length=255, verbose_name='full_name')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
                'db_table': 'content"."person',
            },
        ),
        migrations.CreateModel(
            name='PersonFilmwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True,
                                        serialize=False)),
                ('role', models.CharField(
                    max_length=255, null=True, verbose_name='role')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('film_work', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='movies.filmwork')),
                ('person', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='movies.person')),
            ],
            options={
                'db_table': 'content"."person_film_work',
                'unique_together': {('film_work_id', 'person_id')},
            },
        ),
        migrations.CreateModel(
            name='GenreFilmwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True,
                                        serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('film_work', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='movies.filmwork')),
                ('genre', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='movies.genre')),
            ],
            options={
                'db_table': 'content"."genre_film_work',
            },
        ),
        migrations.AddField(
            model_name='filmwork',
            name='genres',
            field=models.ManyToManyField(
                through='movies.GenreFilmwork', to='movies.genre'),
        ),
        migrations.AddField(
            model_name='filmwork',
            name='persons',
            field=models.ManyToManyField(
                through='movies.PersonFilmwork', to='movies.person'),
        ),
    ]
