# Generated by Django 4.0.3 on 2022-04-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_genrefilmwork_genre_film__film_wo_399489_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(choices=[('director', 'Director'), ('actor', 'Actor'), ('screenwriter', 'Screenwriter')], max_length=255, null=True, verbose_name='role'),
        ),
    ]
